services:
  postgres:
    image: postgres:16
    container_name: anp_fuel_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    container_name: anp_fuel_airflow
    command: standalone
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/airflow_meta
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DBT_PROFILES_DIR: /opt/airflow/project/docker
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/project

volumes:
  pgdata:
